# Generated by Django 5.0.2 on 2024-03-07 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('edad', models.IntegerField(max_length=3)),
                ('esAdmin', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-edad'],
            },
        ),
    ]
