# Generated by Django 5.0.2 on 2024-03-07 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='dni',
            field=models.IntegerField(default='Sin_dni', max_length=10),
        ),
    ]
