# Generated by Django 5.0.2 on 2024-03-07 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miApp', '0002_usuario_dni'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='dni',
            field=models.IntegerField(default=0, max_length=10),
        ),
    ]
