# Generated by Django 5.0.2 on 2024-03-14 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=100)),
                ('categoria', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=100)),
                ('precio', models.IntegerField(max_length=10)),
            ],
        ),
    ]
