# Generated by Django 5.0.2 on 2024-03-13 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='descripcion',
            new_name='color',
        ),
        migrations.AddField(
            model_name='producto',
            name='categoria',
            field=models.CharField(default='default', max_length=100),
        ),
    ]
