# Generated by Django 5.0.2 on 2024-03-14 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miApp', '0002_categoria_alter_producto_descripcion'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Categoria',
        ),
    ]
